### ISSUE TITLE
Find state of the art

### ISSUE THREAD

**Issue by JJ** [MLops-NovaIms/SaveTheWorld-#4]
Use some reference management that can export to BibTex like Mendeley

**Comment by MASOTs** [comment]
https://mdpi-res.com/d_attachment/atmosphere/atmosphere-13-00491/article_deploy/atmosphere-13-00491.pdf?version=1647586476
this is a paper that compares land surface temperature and air temperature

**Comment by danielm09** [comment]
Hey. So, regarding the fire risk analysis, I found that the European Forest Fire Information System (EFFIS) risk assessment is based on a Canadian model (figure below). As we can see, the main variables involved in fire risk assessment are temperature, humidity, rain and wind. I would say we can get rid of the wind, because it seems more complex to handle, and stick with the rest.
![fwi_structure](https://user-images.githubusercontent.com/45716860/178369344-5377f43c-48ee-4869-b98c-d30c2e81c3e7.gif)

**Comment by danielm09** [comment]
Temperature vs wildfire

[https://www.scopus.com/record/display.uri?eid=2-s2.0-85128663625&origin=resultslist&sort=plf-f&src=s&st1=temperature+forecast&sid=1b0671ee0ff29ead3d2127746075611b&sot=b&sdt=b&sl=35&s=TITLE-ABS-KEY%28temperature+forecast%29&relpos=8&citeCnt=0&searchTerm=&featureToggles=FEATURE_NEW_DOC_DETAILS_EXPORT:1](url)

**Comment by danielm09** [comment]
Precipitation prediction - [link](https://www.scopus.com/record/display.uri?eid=2-s2.0-85132983516&origin=resultslist&sort=plf-f&src=s&st1=temperature+AND+precipitation+AND+forecast&sid=98c3460802aa60420d52f81b0f597206&sot=b&sdt=b&sl=57&s=TITLE-ABS-KEY%28temperature+AND+precipitation+AND+forecast%29&relpos=14&citeCnt=0&searchTerm=&featureToggles=FEATURE_NEW_DOC_DETAILS_EXPORT:1)

**Comment by danielm09** [comment]
Rainfall forecast with LSTM - [Link](https://www.scopus.com/record/display.uri?eid=2-s2.0-85131551515&origin=resultslist&sort=plf-f&src=s&st1=temperature+time+series+forecast&nlo=&nlr=&nls=&sid=a96c1ed696f08838b59d77e2822375c3&sot=b&sdt=cl&cluster=scosubtype%2c%22ar%22%2ct&sl=47&s=TITLE-ABS-KEY%28temperature+time+series+forecast%29&relpos=41&citeCnt=0&searchTerm=&featureToggles=FEATURE_NEW_DOC_DETAILS_EXPORT:1)

**Comment by MarouAna** [comment]
https://www.sciencedirect.com/science/article/pii/S0142112322002651
