### ISSUE TITLE
Output of the model

### ISSUE THREAD

**Issue by Rosa-Rafe** [MLops-NovaIms/SaveTheWorld-#47]
For this story, we need the max and min temperature in the year and the precipitation average amount in the year.
Each year will be a vector #1

**Comment by JJ** [comment]
Would it be possible to use temperature and precipitation for several localities? Specially some of them with a real amount of data #48?
Because we will need data from the whole year, or a reasonable substitute, for doing the training. Even if we make some calls for #46 we will not have anything reasonable here.
